### ISSUE TITLE
Protobuf deserialization error

### ISSUE THREAD

**Issue by braddwalker** [braddwalker/ZwiftPacketMonitor#10]
```08:28:46 fail: ZwiftPacketMonitor.Monitor[0] ERROR: PayloadLen: 262, PayloadData: 0104080110965E18939CBBC9DD054A7C0880D0BD8FFAD4BDF3081001186922551097FC661801200A289BB8DBF7C3808080800130003A064D614D614D614204416F6B6948F995BBC9DD0558E8B501600168C8DF027000785A8001018A0114313937302D30312D31335430353A31353A31365A98010028A699BBC9DD054886EEBEC9DD0570D5C586A5AAA4EE024A7808A0F2FDD6FCD4BDF3081001186922511088FE261801200128D9EFBF6A30003A0547656F666642064C69646D616E48B699BBC9DD0558A8E310600168C6DD057000788C018001018A0114313937302D3 Google.Protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).    at Google.Protobuf.ParsingPrimitives.ParseTag(ReadOnlySpan`1& buffer, ParserInternalState& state)    at Google.Protobuf.UnknownFieldSet.MergeGroupFrom(ParseContext& ctx)    at Google.Protobuf.ParsingPrimitivesMessages.ReadGroup(ParseContext& ctx, Int32 fieldNumber, UnknownFieldSet set)    at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(ParseContext& ctx)    at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(UnknownFieldSet unknownFields, ParseContext& ctx)    at ZwiftPacketMonitor.ServerToClient.pb::Google.Protobuf.IBufferMessage.InternalMergeFrom(ParseContext& input)    at Google.Protobuf.CodedInputStream.ReadRawMessage(IMessage message)    at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields, ExtensionRegistry registry)    at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)    at ZwiftPacketMonitor.Monitor.device_OnPacketArrival(Object sender, CaptureEventArgs e)
m.```

**Comment by braddwalker** [comment]
Another instance. I suspect it's related to fragmented packets not getting reassembled correctly.

02:57:23 fail: ZwiftPacketMonitor.Monitor[0] ERROR: PayloadLen: 638, PayloadData: 4F4D50534F4E48CCA5B092DE05588D68600168B88B04700078F3038001008A0114313937302D30312D31335431333A31353A31365A980100289EC6B092DE0548FE9AB492DE0570EDBFEDF9E3A8EE024A7208D091D2EDADAAE1F50810011869224B10EEB75B18012001280130003A054D696C616E4205536176617348E8E3FFCABFE72C5800600168E0D104700078008001018A0114313937302D30312D31335431333A31353A31365A980100289EC6B092DE0548FE9AB492DE05709EC6EDF9E3A8EE024A7508E0BDE2E2AEAAE1F50810011869224E10B882D3011801200128C99AD2E60330003A05416E6472794202462E48D8C2B092DE0558E5A303600168B8B3047000787A8001018A0114313937302D30312D31335431313A31353A31365A98010028BBC6B092DE05489B9BB492DE057091B0EFF9E3A8EE024A7A08E091D2EDAEAAE1F50810011869225310FEDC7B1801200328EEBA9CF893808080800130003A0344616E420542616E6B7348FCB5B092DE0558E762600168F09F05700078F6048001018A0114313937302D30312D31335431333A31353A31365A98010028BEC6B092DE05489E9BB492DE0570C5D1EFF9E3A8EE024A7508C0FBBDB3AFAAE1F50810011869224E1088E8211801200128DAEFBF6A30003A014A4208436F6F6B2055313248A2C4B092DE0558EEAD24600168C0B802700078598001008A0114313937302D30312D31335431333A31353A31365A98010028CFC6B092DE0548AF9BB492DE0570A9D0F0F9E3A8EE024A4F08B0CFB0D7AFAAE1F5081001186D222801002400 Google.Protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.    at Google.Protobuf.ParsingPrimitives.ValidateCurrentLimit(ReadOnlySpan`1& buffer, ParserInternalState& state, Int32 size)    at Google.Protobuf.ParsingPrimitives.ReadRawBytesSlow(ReadOnlySpan`1& buffer, ParserInternalState& state, Int32 size)    at Google.Protobuf.ParsingPrimitives.ReadRawBytes(ReadOnlySpan`1& buffer, ParserInternalState& state, Int32 size)    at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(ParseContext& ctx)    at Google.Protobuf.UnknownFieldSet.MergeFieldFrom(UnknownFieldSet unknownFields, ParseContext& ctx)    at ZwiftPacketMonitor.PlayerUpdate.pb::Google.Protobuf.IBufferMessage.InternalMergeFrom(ParseContext& input) in /Users/bradwalker/Documents/Source/ZwiftPacketMonitor/src/ZwiftMessages.cs:line 2555    at Google.Protobuf.ParsingPrimitivesMessages.ReadMessage(ParseContext& ctx, IMessage message)    at Google.Protobuf.FieldCodec.<>c__DisplayClass32_0`1.<ForMessage>b__0(ParseContext& ctx)    at Google.Protobuf.Collections.RepeatedField`1.AddEntriesFrom(ParseContext& ctx, FieldCodec`1 codec)    at ZwiftPacketMonitor.ServerToClient.pb::Google.Protobuf.IBufferMessage.InternalMergeFrom(ParseContext& input) in /Users/bradwalker/Documents/Source/ZwiftPacketMonitor/src/ZwiftMessages.cs:line 5795    at Google.Protobuf.CodedInputStream.ReadRawMessage(IMessage message)    at ZwiftPacketMonitor.ServerToClient.MergeFrom(CodedInputStream input) in /Users/bradwalker/Documents/Source/ZwiftPacketMonitor/src/ZwiftMessages.cs:line 5705    at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields, ExtensionRegistry registry)    at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)    at ZwiftPacketMonitor.Monitor.device_OnPacketArrival(Object sender, CaptureEventArgs e) in /Users/bradwalker/Documents/Source/ZwiftPacketMonitor/src/Monitor.cs:line 394

02:57:31 fail: ZwiftPacketMonitor.Monitor[0] ERROR: PayloadLen: 1125, PayloadData: 0463080110965E18C5FBB092DE054A7D0880D0E2EAFAABE1F50810011869225610B5935B180120012891D9FEA80830A5BD763A07416E64726561734207466173736F6C6448EDF4B092DE0558BBDB12600168D08005700078738001018A0114313937302D30312D31335431333A31353A31365A98010028BDF9B092DE05489DCEB492DE05708FF8FDFCE3A8EE024A7E0890D0E2FEFAABE1F50810011869225710C392171801200128DAEFBF6A30003A055374616369420D4D757270687920285754524C294880D0EF90DE0558B39928600168FD9303700078518001008A0114313937302D30312D31335431393A31353A31365A98010028C2F9B092DE0548A2CEB492DE0570B498FEFCE3A8EE024A7A08C0BEFDDAFBABE1F50810011869225310D083D5011801200A2895C2DFF90330003A044E69636B42074865726D616E7348EBF6B092DE0558C29301600168A8BA04700078D2018001018A0114313937302D30312D31335431333A31353A31365A98010028D9F9B092DE0548B9CEB492DE0570FFCDFFFCE3A8EE024A4F08A0A1D2D9FBABE1F5081001186D2228010024000000000018FD000000000000F9721C000000000000010000000000008941A0B81A7EA74128D9F9B092DE0548B9CEB492DE0570FAD2FFFCE3A8EE024A850108B0D790BCFCABE1F50810011869225E10F69054180120012880D9FEA80830003A124368726973746F7068205B522E4C47535A5D42055A697A657248C7F7B092DE0558AEF506600168C0B204700078BC018001018A0114313937302D30312D31335431333A31353A31365A98010028F2F9B092DE0548D2CEB492DE0570CB8D81FDE3A8EE024A6D08C0D790D8FCABE1F50810011869224610A8AC561801200A280130003A04746F6D6F4201734890C199CEBFE72C5800600168E8FB03700078008001018A0114313937302D30312D31335430353A31353A31365A98010028F9F9B092DE0548D9CEB492DE05708CCD81FDE3A8EE024A920108E0BEFDB2FDABE1F50810011869226B10A48EB0011801200B2881E88EF993808080800130003A0120421E54686520526163696E6720446976612028436F66666565636861696E73294893F3B092DE0558DEF80160016880F1047000786F8001018A0114313937302D30312D31335431333A31353A31365A980100288FFAB092DE0548EFCEB492DE0570D6ED82FDE3A8EE024A7708C0D0E2F6FEABE1F50810011869225010DCE0651801200B280130003A064F6C697665724209506174746572736F6E48C8FC8DCEBFE72C5800600168E9DE02700078008001018A0114313937302D30312D31335431333A31353A31365A98010028C0FAB092DE0548A0CFB492DE05709E8186FDE3A8EE024A830108E0D5C6B2FFABE1F50810011869225C10F099271801200128C99AD2E60330003A0C54C3B36D617320487261666E4209537665696E73736F6E48D9F7B092DE0558FB9803600168C0B50370007889018001018A0114313937302D30312D31335431343A31353A31365A98010028CFFAB092DE0548AFCFB492DE0570C7E986FD Google.Protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).    at Google.Protobuf.ParsingPrimitives.ParseTag(ReadOnlySpan`1& buffer, ParserInternalState& state)    at Google.Protobuf.ParsingPrimitives.PeekTag(ReadOnlySpan`1& buffer, ParserInternalState& state)    at Google.Protobuf.Collections.RepeatedField`1.AddEntriesFrom(ParseContext& ctx, FieldCodec`1 codec)    at ZwiftPacketMonitor.ServerToClient.pb::Google.Protobuf.IBufferMessage.InternalMergeFrom(ParseContext& input) in /Users/bradwalker/Documents/Source/ZwiftPacketMonitor/src/ZwiftMessages.cs:line 5795    at Google.Protobuf.CodedInputStream.ReadRawMessage(IMessage message)    at ZwiftPacketMonitor.ServerToClient.MergeFrom(CodedInputStream input) in /Users/bradwalker/Documents/Source/ZwiftPacketMonitor/src/ZwiftMessages.cs:line 5705    at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data, Boolean discardUnknownFields, ExtensionRegistry registry)    at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)    at ZwiftPacketMonitor.Monitor.device_OnPacketArrival(Object sender, CaptureEventArgs e) in /Users/bradwalker/Documents/Source/ZwiftPacketMonitor/src/Monitor.cs:line 394
